name: "Goofy's Vest"
favicon: null
layout_spectrum: 0.9114781867247075
typography_spectrum: 0.4682929920963943
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ff7e00'
    - '#3a3a3c'
    - '#f1f1f3'
    - '#a1561a'
  brandStrength: 0.35817617108114064
  lightness: 0.9628732753917575
  saturation: 0.4426056982483715
  rhythmicContrast: 0.8331323782913387
purpose: []
